### ISSUE TITLE
prompt_code/model.py 文件似乎有一些问题。

### ISSUE THREAD

**Issue by Ferliuc** [siyuyuan/KPCE#1]
model.py 文件里的Prompt_MRCModel类下的generate_default_inputs()函数里有一行好像写错了？
原代码为：        
input_embeds = tensor.cat((topic_embeds,raw_embeds),1)
修改为：
input_embeds = torch.cat((topic_embeds,raw_embeds),1)
才可正常运行。

**Comment by siyuyuan** [comment]
> 

好滴，我改一下~谢谢你:)

**Comment by GitHubwwZ** [comment]
> model.py 文件里的Prompt_MRCModel类下的generate_default_inputs()函数里有一行好像写错了？ 原代码为： input_embeds = tensor.cat((topic_embeds,raw_embeds),1) 修改为： input_embeds = torch.cat((topic_embeds,raw_embeds),1) 才可正常运行。

哈喽，您在用这个代码进行概念抽取吗？方便请教个问题吗，替换成自己的数据进行预测时，您有遇到过抽取的结果只有单个字而不是概念词语的问题吗？（下图这个形式）
<img width="784" alt="未命名图片" src="https://github.com/siyuyuan/KPCE/assets/45789033/dd4913e7-9dcb-4488-9b65-e23e5ceb8e6b">

**Comment by GitHubwwZ** [comment]
> model.py 文件里的Prompt_MRCModel类下的generate_default_inputs()函数里有一行好像写错了？ 原代码为： input_embeds = tensor.cat((topic_embeds,raw_embeds),1) 修改为： input_embeds = torch.cat((topic_embeds,raw_embeds),1) 才可正常运行。

哈喽，您在用这个代码进行概念抽取吗？方便请教个问题吗，替换成自己的数据进行预测时，您有遇到过抽取的结果只有单个字而不是概念词语的问题吗？（下图这个形式）
<img width="784" alt="未命名图片" src="https://github.com/siyuyuan/KPCE/assets/45789033/d72aadb9-26bd-48f2-815c-7387c22dfe70">
