### ISSUE TITLE
KPCE预测

### ISSUE THREAD

**Issue by GitHubwwZ** [siyuyuan/KPCE#2]
请问目前代码支持预测或者训练自己的数据集吗？论文里提到的评价指标的运行结果包含在代码里面吗，在哪里查看呢，还是需要自己实现呢？

**Comment by siyuyuan** [comment]
> 请问目前代码支持预测或者训练自己的数据集吗？论文里提到的评价指标的运行结果包含在代码里面吗，在哪里查看呢，还是需要自己实现呢？

您好，依照训练代码和数据集格式可以训练自己的数据集。评价指标包含基础的precision，recall和f1直接按照标准的实现即可。

**Comment by GitHubwwZ** [comment]
> > 请问目前代码支持预测或者训练自己的数据集吗？论文里提到的评价指标的运行结果包含在代码里面吗，在哪里查看呢，还是需要自己实现呢？
> 
> 您好，依照训练代码和数据集格式可以训练自己的数据集。评价指标包含基础的precision，recall和f1直接按照标准的实现即可。

好的，谢谢！！

**Comment by GitHubwwZ** [comment]
关于预测，还有个问题🙋
我想用您的数据做训练，我的数据（长文本 见图1）做预测，怎么转化成数据集中test.txt（见图2）的格式呢？数据量太大自己标注不太好操作，想参考一下，您处理美团数据的时候怎么转换成test.txt数据集中的格式？
麻烦了，感谢🙏
<img width="1151" alt="我的数据" src="https://github.com/siyuyuan/KPCE/assets/45789033/c0b48286-c542-4e5c-8a10-12c82fd0c432">
<img width="1214" alt="数据集test txt格式" src="https://github.com/siyuyuan/KPCE/assets/45789033/11827151-c54d-4fff-80e2-c307bfe8fb80">

**Comment by siyuyuan** [comment]
> 关于预测，还有个问题🙋 我想用您的数据做训练，我的数据（长文本 见图1）做预测，怎么转化成数据集中test.txt（见图2）的格式呢？数据量太大自己标注不太好操作，想参考一下，您处理美团数据的时候怎么转换成test.txt数据集中的格式？ 麻烦了，感谢🙏 <img alt="我的数据" width="1151" src="https://private-user-images.githubusercontent.com/45789033/289223764-c0b48286-c542-4e5c-8a10-12c82fd0c432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjQtYzBiNDgyODYtYzU0Mi00ZTVjLThhMTAtMTJjODJmZDBjNDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NGI3OTBhYmNhZjY5NDRmZTdmZDYyODMwMjNkNWQwNjFiNmUwYTgzNzU3NGFhNzgyZWVjMjFiYzcyY2ViYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.etHkxucxpSCkL7Av24h4z7WStMmPV3XnWJBVbTSdqRY"> <img alt="数据集test txt格式" width="1214" src="https://private-user-images.githubusercontent.com/45789033/289223765-11827151-c54d-4fff-80e2-c307bfe8fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjUtMTE4MjcxNTEtYzU0ZC00ZmZmLTgwZTItYzMwN2JmZThmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMWY0NzJiYzc4NDE5NTE4Y2JjZDVhZmEwMTYxZjk1MjFlZGIzNTg3NmRjNzU1MjJjODNjMjNkMTAxNjNjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VPkCHr8iqXY3-agca3HWYl61t9l1-T5hNpZ97D1XFBw">

你好，
test set后面的标注其实并不需要因为本身就是预测，可以随机生成。

**Comment by GitHubwwZ** [comment]
> > 关于预测，还有个问题🙋 我想用您的数据做训练，我的数据（长文本 见图1）做预测，怎么转化成数据集中test.txt（见图2）的格式呢？数据量太大自己标注不太好操作，想参考一下，您处理美团数据的时候怎么转换成test.txt数据集中的格式？ 麻烦了，感谢🙏 <img alt="我的数据" width="1151" src="https://private-user-images.githubusercontent.com/45789033/289223764-c0b48286-c542-4e5c-8a10-12c82fd0c432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjQtYzBiNDgyODYtYzU0Mi00ZTVjLThhMTAtMTJjODJmZDBjNDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NGI3OTBhYmNhZjY5NDRmZTdmZDYyODMwMjNkNWQwNjFiNmUwYTgzNzU3NGFhNzgyZWVjMjFiYzcyY2ViYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.etHkxucxpSCkL7Av24h4z7WStMmPV3XnWJBVbTSdqRY"> <img alt="数据集test txt格式" width="1214" src="https://private-user-images.githubusercontent.com/45789033/289223765-11827151-c54d-4fff-80e2-c307bfe8fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjUtMTE4MjcxNTEtYzU0ZC00ZmZmLTgwZTItYzMwN2JmZThmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMWY0NzJiYzc4NDE5NTE4Y2JjZDVhZmEwMTYxZjk1MjFlZGIzNTg3NmRjNzU1MjJjODNjMjNkMTAxNjNjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VPkCHr8iqXY3-agca3HWYl61t9l1-T5hNpZ97D1XFBw">
> 
> 你好， test set后面的标注其实并不需要因为本身就是预测，可以随机生成。

我开始也是这么理解的，但是直接把我的数据替换到test.txt中，因为格式不对会报错。
如果按您上面的思路，用您上传的代码可以直接实现吗？怎么操作呢？

**Comment by siyuyuan** [comment]
> > > 关于预测，还有个问题🙋 我想用您的数据做训练，我的数据（长文本 见图1）做预测，怎么转化成数据集中test.txt（见图2）的格式呢？数据量太大自己标注不太好操作，想参考一下，您处理美团数据的时候怎么转换成test.txt数据集中的格式？ 麻烦了，感谢🙏 <img alt="我的数据" width="1151" src="https://private-user-images.githubusercontent.com/45789033/289223764-c0b48286-c542-4e5c-8a10-12c82fd0c432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjQtYzBiNDgyODYtYzU0Mi00ZTVjLThhMTAtMTJjODJmZDBjNDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NGI3OTBhYmNhZjY5NDRmZTdmZDYyODMwMjNkNWQwNjFiNmUwYTgzNzU3NGFhNzgyZWVjMjFiYzcyY2ViYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.etHkxucxpSCkL7Av24h4z7WStMmPV3XnWJBVbTSdqRY"> <img alt="数据集test txt格式" width="1214" src="https://private-user-images.githubusercontent.com/45789033/289223765-11827151-c54d-4fff-80e2-c307bfe8fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjUtMTE4MjcxNTEtYzU0ZC00ZmZmLTgwZTItYzMwN2JmZThmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMWY0NzJiYzc4NDE5NTE4Y2JjZDVhZmEwMTYxZjk1MjFlZGIzNTg3NmRjNzU1MjJjODNjMjNkMTAxNjNjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VPkCHr8iqXY3-agca3HWYl61t9l1-T5hNpZ97D1XFBw">
> > 
> > 
> > 你好， test set后面的标注其实并不需要因为本身就是预测，可以随机生成。
> 
> 我开始也是这么理解的，但是直接把我的数据替换到test.txt中，因为格式不对会报错。 如果按您上面的思路，用您上传的代码可以直接实现吗？怎么操作呢？

直接转换是可以的，可以看一下代码。

**Comment by GitHubwwZ** [comment]
> > > > 关于预测，还有个问题🙋 我想用您的数据做训练，我的数据（长文本 见图1）做预测，怎么转化成数据集中test.txt（见图2）的格式呢？数据量太大自己标注不太好操作，想参考一下，您处理美团数据的时候怎么转换成test.txt数据集中的格式？ 麻烦了，感谢🙏 <img alt="我的数据" width="1151" src="https://private-user-images.githubusercontent.com/45789033/289223764-c0b48286-c542-4e5c-8a10-12c82fd0c432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjQtYzBiNDgyODYtYzU0Mi00ZTVjLThhMTAtMTJjODJmZDBjNDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NGI3OTBhYmNhZjY5NDRmZTdmZDYyODMwMjNkNWQwNjFiNmUwYTgzNzU3NGFhNzgyZWVjMjFiYzcyY2ViYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.etHkxucxpSCkL7Av24h4z7WStMmPV3XnWJBVbTSdqRY"> <img alt="数据集test txt格式" width="1214" src="https://private-user-images.githubusercontent.com/45789033/289223765-11827151-c54d-4fff-80e2-c307bfe8fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM5MjgsIm5iZiI6MTcwMjA5MzYyOCwicGF0aCI6Ii80NTc4OTAzMy8yODkyMjM3NjUtMTE4MjcxNTEtYzU0ZC00ZmZmLTgwZTItYzMwN2JmZThmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMWY0NzJiYzc4NDE5NTE4Y2JjZDVhZmEwMTYxZjk1MjFlZGIzNTg3NmRjNzU1MjJjODNjMjNkMTAxNjNjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VPkCHr8iqXY3-agca3HWYl61t9l1-T5hNpZ97D1XFBw">
> > > 
> > > 
> > > 你好， test set后面的标注其实并不需要因为本身就是预测，可以随机生成。
> > 
> > 
> > 我开始也是这么理解的，但是直接把我的数据替换到test.txt中，因为格式不对会报错。 如果按您上面的思路，用您上传的代码可以直接实现吗？怎么操作呢？
> 
> 直接转换是可以的，可以看一下代码。

好的好的，我再仔细看看。多谢！！🙏

**Comment by GitHubwwZ** [comment]
我用2w条做训练，训练1轮。测试集用自己的数据，训练结果抽取的概念怎么都是'[SEP]'（每条数据我取了概率最大的一个概念输出 见下图），是哪里设定有问题吗？
<img width="1024" alt="截屏2023-12-09 17 56 44" src="https://github.com/siyuyuan/KPCE/assets/45789033/63b753a9-6cf1-43c6-bb86-f1968c746a48">

**Comment by GitHubwwZ** [comment]
您好，我用自己的数据做预测时，跑出来的概念都是单个字而不是词语，请问是哪里设置的有问题吗？
<img width="784" alt="未命名图片" src="https://github.com/siyuyuan/KPCE/assets/45789033/795e1dcd-39e4-4d2e-887c-ec3a76abac43">
